title: "Test demo project"
description: "etc."

commands:

  - name: "run_me"
    help: "Run me"
    script:
      - "python -m spacy download 'en_core_web_sm'"


  - name: "mk_dirs"
    script:
      - "mkdir testing_some_stuff"
      - "mkdir testing_more_stuff"


  - name: "rm_dirs"
    script:
      - "rm -rf testing_*_stuff"
